### ISSUE TITLE
module name mismatches when importing

### ISSUE THREAD

**Issue by kha7iq** [Cyberax/go-nfs-client#3]
Even though the fixed was introduced in another issue https://github.com/Cyberax/go-nfs-client/issues/1
A new release was never created so when importing this package go will fetch version  [v1.0.0](https://github.com/Cyberax/go-nfs-client/releases/tag/v1.0.0) which contain `aurorasolar/go-nfs-client` in code and produces following error
```bash
go get github.com/Cyberax/go-nfs-client/nfs4
go: github.com/Cyberax/go-nfs-client@v1.0.0: parsing go.mod:
        module declares its path as: github.com/aurorasolar/go-nfs-client
                but was required as: github.com/Cyberax/go-nfs-client
```
@Cyberax  can you create a new release

**Comment by kha7iq** [comment]
Closing, as using the fork of this now

**Comment by aep** [comment]
> Closing, as using the fork of this now

~~which fork?~~

oh i guess you're the maintainer now :D

https://github.com/kha7iq/go-nfs-client


will you accept PRs?
